# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = ''

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_name', models.CharField(max_length=100)),
                ('constant_value', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('date_updated', models.DateField(max_length=100, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'constant',
            },
        ),
    ]
