# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0002_auto_20200607_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='constant_value',
            field=models.FloatField(null=True),
        ),
    ]
