# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0003_auto_20200607_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
