# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-07 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBasedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateTimeField(max_length=30)),
                ('clientele_id', models.IntegerField(max_length=10)),
                ('clientele_name', models.CharField(max_length=20)),
                ('expense_based_id_number', models.IntegerField()),
                ('rate', models.IntegerField(max_length=20)),
                ('quantity', models.IntegerField(max_length=20)),
                ('narration', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField(max_length=20)),
                ('transaction_reference', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('original_approved_date', models.DateTimeField(max_length=30)),
                ('date_approved', models.DateTimeField(max_length=30)),
                ('transaction_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('expense based', 'Expense-Based'), ('foreb debt', 'Foreb Debt Repayment'), ('customer debt', 'Customer Debt Repayment')], max_length=20)),
            ],
            options={
                'db_table': 'expense_based_transactions',
            },
        ),
    ]
