# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='clientele_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='total_cost',
            field=models.IntegerField(),
        ),
    ]
