# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200507_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebasedtransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='clientele_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='date_approved',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='date_initiated',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='expense_based_id_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='original_approved_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
