# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-09 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200509_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebasedtransaction',
            name='clientele_id',
        ),
    ]
