# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-10 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200510_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=20, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_approved_date', models.DateTimeField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'transactions_record',
            },
        ),
    ]
