# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='date_initiated',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='eb_client',
            field=models.CharField(choices=[('5', 'Ekedc'), ('9', 'Diesel'), ('10', 'Petrol')], max_length=20, null=True),
        ),
    ]
