# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200510_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebtTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateField(max_length=30, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=20)),
                ('clientele_id', models.IntegerField(null=True)),
                ('clientele_name', models.CharField(max_length=20)),
                ('amount_paid', models.IntegerField(null=True)),
                ('narration', models.CharField(choices=[('part payment', 'Part Payment of Money Owed'), ('full payment', 'Full Payment of Money Owed')], max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('original_approved_date', models.DateTimeField(max_length=30, null=True)),
                ('date_approved', models.DateTimeField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'customer_debt_transactions',
            },
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='eb_client',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
