# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200513_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForebDebtTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateField(max_length=30, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=20)),
                ('clientele_id', models.IntegerField(null=True)),
                ('clientele_name', models.CharField(max_length=20)),
                ('amount_paid', models.IntegerField(null=True)),
                ('narration', models.CharField(choices=[('part payment', 'Part Payment of Money Owed Customer'), ('full payment', 'Full Payment of Money Owed Customer')], max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('original_approved_date', models.DateTimeField(max_length=30, null=True)),
                ('date_approved', models.DateTimeField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'foreb_debt_transactions',
            },
        ),
    ]
