# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_forebdebttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateField(max_length=30, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=20, null=True)),
                ('clientele_id', models.IntegerField(null=True)),
                ('clientele_name', models.CharField(max_length=20)),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=100)),
                ('diesel_rate', models.IntegerField(null=True)),
                ('diesel_litres', models.IntegerField(null=True)),
                ('diesel_value', models.IntegerField(null=True)),
                ('other_costs', models.IntegerField(null=True)),
                ('product_rate', models.IntegerField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_discount', models.IntegerField(null=True)),
                ('deductions', models.IntegerField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('quantity_value', models.IntegerField(null=True)),
                ('expected_oil', models.IntegerField(null=True)),
                ('expected_cake', models.IntegerField(null=True)),
                ('cake_value', models.IntegerField(null=True)),
                ('transaction_income', models.IntegerField(null=True)),
                ('transaction_cost', models.IntegerField(null=True)),
                ('approved_status', models.CharField(max_length=20)),
                ('gen_diesel_litres', models.IntegerField(null=True)),
                ('gen_diesel_rate', models.IntegerField(null=True)),
                ('gen_diesel_value', models.IntegerField(null=True)),
                ('waybill_number', models.IntegerField(null=True)),
                ('original_approved_date', models.DateTimeField(max_length=30, null=True)),
                ('date_approved', models.DateTimeField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'purchase_transactions',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initiated', models.DateField(max_length=30, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=20, null=True)),
                ('clientele_id', models.IntegerField(null=True)),
                ('clientele_name', models.CharField(max_length=20)),
                ('product_id', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=100)),
                ('diesel_rate', models.IntegerField(null=True)),
                ('diesel_value', models.IntegerField(null=True)),
                ('diesel_litres', models.IntegerField(null=True)),
                ('other_costs', models.IntegerField(null=True)),
                ('product_rate', models.IntegerField(null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_discount', models.IntegerField(null=True)),
                ('deductions', models.IntegerField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('quantity_value', models.IntegerField(null=True)),
                ('expected_oil', models.IntegerField(null=True)),
                ('expected_cake', models.IntegerField(null=True)),
                ('cake_value', models.IntegerField(null=True)),
                ('transaction_income', models.IntegerField(null=True)),
                ('transaction_cost', models.IntegerField(null=True)),
                ('approved_status', models.CharField(max_length=20)),
                ('gen_diesel_litres', models.IntegerField(null=True)),
                ('gen_diesel_rate', models.IntegerField(null=True)),
                ('gen_diesel_value', models.IntegerField(null=True)),
                ('waybill_number', models.IntegerField(null=True)),
                ('Docket_number', models.IntegerField(null=True)),
                ('original_approved_date', models.DateTimeField(max_length=30, null=True)),
                ('date_approved', models.DateTimeField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'sales_transactions',
            },
        ),
    ]
