# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20200526_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensebasedtransaction',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
