# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_expensebasedtransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebasedtransaction',
            name='expense_based_id_number',
        ),
        migrations.AddField(
            model_name='expensebasedtransaction',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='expensebasedtransaction',
            table='expense_based_transaction',
        ),
    ]
