# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-02 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20200601_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebttransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forebdebttransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
