# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20200604_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetransaction',
            name='approved_status',
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='cake_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='deductions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='diesel_litres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='diesel_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='diesel_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='expected_cake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='expected_oil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='gen_diesel_litres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='gen_diesel_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='gen_diesel_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='other_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='product_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='waybill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
