# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20200608_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='cake_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
