# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20200608_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='other_costs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
