# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_auto_20200608_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='clientele_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
