# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20200608_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='total_cost',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
