# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_auto_20200610_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebasedtransaction',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
