# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_auto_20200611_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
