# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_auto_20200611_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='clientele_id',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
