# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_transactionrecord_clientele_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebasedtransaction',
            name='eb_client',
        ),
        migrations.AddField(
            model_name='expensebasedtransaction',
            name='clientele_id',
            field=models.IntegerField(null=True),
        ),
    ]
