# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_auto_20200611_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
    ]
