# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_auto_20200614_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='approved_by',
            field=models.CharField(default='admin', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_approved_date',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
