# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_auto_20200614_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebttransaction',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
    ]
