# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientele_name', models.CharField(help_text='Clientele Name', max_length=100)),
                ('clientele_type', models.CharField(choices=[('supplier', 'supplier'), ('customer', 'customer'), ('both', 'both')], max_length=20)),
                ('clientele_address', models.CharField(max_length=20)),
                ('clientele_contact_number', models.CharField(max_length=20)),
                ('clientele_email', models.EmailField(blank=True, max_length=254)),
                ('clientele_wallet_balance', models.FloatField(max_length=20)),
            ],
            options={
                'db_table': 'clientele',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_paid', models.DateField()),
                ('amount', models.FloatField()),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Clientele')),
            ],
        ),
    ]
