# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_auto_20200507_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('buyer', 'Buyer'), ('both', 'Both'), ('eb client', 'Expense-Based Clients')], max_length=20),
        ),
    ]
