# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0003_auto_20200526_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='clientele',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
