# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0004_auto_20200601_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientele',
            name='clientele_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clientele',
            name='clientele_wallet_balance',
            field=models.FloatField(blank=True, max_length=20),
        ),
    ]
