# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0005_auto_20200607_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
