# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0007_auto_20200607_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_name',
            field=models.CharField(help_text='Clientele Name', max_length=100, unique=True),
        ),
    ]
