# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0008_auto_20200608_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_name',
            field=models.CharField(help_text='Clientele Name', max_length=100),
        ),
    ]
