# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0009_auto_20200610_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientele',
            name='clientele_type',
            field=models.CharField(max_length=20),
        ),
    ]
