# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0010_auto_20200612_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientele',
            name='default_wallet_balance',
            field=models.FloatField(default=1, null=True),
        ),
    ]
