# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0012_auto_20200614_0523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientele',
            options={'ordering': ('clientele_name',)},
        ),
        migrations.AlterField(
            model_name='clientele',
            name='default_wallet_balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
